name: Lean.OpenWRT-X86_64

on:
  schedule:
    - cron: '00 10 * * *'
  watch:
   types: started

jobs:
  build:
    name: Build OpenWRT
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Init Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo apt-get update
          sudo apt-get -y upgrade
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig
          sudo apt-get -y autoremove --purge
          sudo apt-get clean
          
      - name: Get Source Code
        run: |
          git clone https://github.com/coolsnowwolf/lede.git
          cd lede/
          sed -i 's/#src-git/src-git/g' feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          
      - name: Customization Configuration
        run: |
          cp config/CONFIG_X86_64 lede/.config
          chmod +x config/Customize.sh && sh config/Customize.sh
          
      - name: Build OpenWRT
        run: |
          cd lede/
          make defconfig
          make download -j8
          find dl -size -1024c -exec rm -f {} \;
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin
          
      - name: Upload Artifact All
        uses: actions/upload-artifact@master
        with:
          name: Lean.OpenWRT-X86_64.All
          path: lede/bin/
